services:
  app:
    build:
      context: app
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/app
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
